name: Build App
on:
  push:
    branches: [ 'master', 'main', 'prod', 'production' ]

jobs:
  job:
    name: windows build
    runs-on: windows-latest
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Install packages and dependencies
        run: |
          bootstrap-vcpkg
          vcpkg integrate install

      - name: Build app for release
        run: msbuild DOGEngine\DOGEngine.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Push to Itch.io
        run: |
          butler push D:\a\DOGEngine\DOGEngine\DOGEngine\Release\ bioblaze/dogengine:windows-alpha