name: Build App
on:
  push:
    branches: [ 'master', 'main', 'prod', 'production' ]

jobs:
  job:
    name: windows build
    runs-on: windows-latest
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      # New step to run SetupButler.ps1
      - name: Setup Butler
        run: .\Tools\Windows\SetupButler.ps1
        shell: pwsh

      - name: Install packages and dependencies
        run: |
          bootstrap-vcpkg
          vcpkg integrate install

      - name: Build app for release
        run: msbuild DOGEngine.sln -t:build -verbosity:diag /p:Configuration=Release /p:Platform=x64 /p:ClCompile_AdditionalOptions="/std:c++17 %(ClCompile_AdditionalOptions)"

      - name: Push to Itch.io
        run: |
          D:\a\DOGEngine\DOGEngine\butler\butler.exe push D:\a\DOGEngine\DOGEngine\DOGEngine\Release\ bioblaze/dogengine:windows-alpha